use_frameworks!

target 'FormBuilder_Example' do
  pod 'FormBuilder', :path => '../'

  target 'FormBuilder_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
