use_frameworks!

target 'FormBuilder_Example' do
  pod 'FormBuilder', :path => '../'

  target 'FormBuilder_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
